rom_config: ../../../extract/usa/config.yaml
build_path: ../../../build/usa
delinks_path: ../../../build/usa/delinks
enable_dsprot: true
main_module:
  name: main
  object: ../../../build/usa/build/arm9.bin
  hash: dd37b383d94a72d0
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
  - kind: Itcm
    name: itcm
    object: ../../../build/usa/build/itcm.bin
    hash: 6b49249cfc6b2b50
    delinks: itcm/delinks.txt
    symbols: itcm/symbols.txt
    relocations: itcm/relocs.txt
  - kind: Dtcm
    name: dtcm
    object: ../../../build/usa/build/dtcm.bin
    hash: 185e21f377d356e3
    delinks: dtcm/delinks.txt
    symbols: dtcm/symbols.txt
    relocations: dtcm/relocs.txt
overlays:
  - id: 0
    signed: true
    name: ov000
    object: ../../../build/usa/build/arm9_ov000.bin
    hash: 5442901954e019ad
    delinks: overlays/ov000/delinks.txt
    symbols: overlays/ov000/symbols.txt
    relocations: overlays/ov000/relocs.txt
  - id: 1
    signed: true
    name: ov001
    object: ../../../build/usa/build/arm9_ov001.bin
    hash: fc67da32559ff299
    delinks: overlays/ov001/delinks.txt
    symbols: overlays/ov001/symbols.txt
    relocations: overlays/ov001/relocs.txt
  - id: 2
    signed: true
    name: ov002
    object: ../../../build/usa/build/arm9_ov002.bin
    hash: e0dd7ad74018b252
    delinks: overlays/ov002/delinks.txt
    symbols: overlays/ov002/symbols.txt
    relocations: overlays/ov002/relocs.txt
  - id: 3
    signed: true
    name: ov003
    object: ../../../build/usa/build/arm9_ov003.bin
    hash: 6fa2f5df1196923f
    delinks: overlays/ov003/delinks.txt
    symbols: overlays/ov003/symbols.txt
    relocations: overlays/ov003/relocs.txt
  - id: 4
    signed: true
    name: ov004
    object: ../../../build/usa/build/arm9_ov004.bin
    hash: c1bed8db424c839c
    delinks: overlays/ov004/delinks.txt
    symbols: overlays/ov004/symbols.txt
    relocations: overlays/ov004/relocs.txt
  - id: 5
    signed: true
    name: ov005
    object: ../../../build/usa/build/arm9_ov005.bin
    hash: a7c0948c3254a9ac
    delinks: overlays/ov005/delinks.txt
    symbols: overlays/ov005/symbols.txt
    relocations: overlays/ov005/relocs.txt
  - id: 6
    signed: true
    name: ov006
    object: ../../../build/usa/build/arm9_ov006.bin
    hash: 86046bc92be85551
    delinks: overlays/ov006/delinks.txt
    symbols: overlays/ov006/symbols.txt
    relocations: overlays/ov006/relocs.txt
  - id: 7
    signed: true
    name: ov007
    object: ../../../build/usa/build/arm9_ov007.bin
    hash: f91892c3363a6c1b
    delinks: overlays/ov007/delinks.txt
    symbols: overlays/ov007/symbols.txt
    relocations: overlays/ov007/relocs.txt
  - id: 8
    signed: true
    name: ov008
    object: ../../../build/usa/build/arm9_ov008.bin
    hash: 70e917c80a1996e7
    delinks: overlays/ov008/delinks.txt
    symbols: overlays/ov008/symbols.txt
    relocations: overlays/ov008/relocs.txt
  - id: 9
    signed: true
    name: ov009
    object: ../../../build/usa/build/arm9_ov009.bin
    hash: 625aab498b9231ce
    delinks: overlays/ov009/delinks.txt
    symbols: overlays/ov009/symbols.txt
    relocations: overlays/ov009/relocs.txt
  - id: 10
    signed: true
    name: ov010
    object: ../../../build/usa/build/arm9_ov010.bin
    hash: 0cd67f9c2a7e8a63
    delinks: overlays/ov010/delinks.txt
    symbols: overlays/ov010/symbols.txt
    relocations: overlays/ov010/relocs.txt
  - id: 11
    signed: true
    name: ov011
    object: ../../../build/usa/build/arm9_ov011.bin
    hash: bda1cd7f479ff48e
    delinks: overlays/ov011/delinks.txt
    symbols: overlays/ov011/symbols.txt
    relocations: overlays/ov011/relocs.txt
  - id: 12
    signed: true
    name: ov012
    object: ../../../build/usa/build/arm9_ov012.bin
    hash: 9e8c3cb6af0d02a2
    delinks: overlays/ov012/delinks.txt
    symbols: overlays/ov012/symbols.txt
    relocations: overlays/ov012/relocs.txt
  - id: 13
    signed: true
    name: ov013
    object: ../../../build/usa/build/arm9_ov013.bin
    hash: 06d499779b66db30
    delinks: overlays/ov013/delinks.txt
    symbols: overlays/ov013/symbols.txt
    relocations: overlays/ov013/relocs.txt
  - id: 14
    signed: true
    name: ov014
    object: ../../../build/usa/build/arm9_ov014.bin
    hash: 191d8eda93bed31d
    delinks: overlays/ov014/delinks.txt
    symbols: overlays/ov014/symbols.txt
    relocations: overlays/ov014/relocs.txt
  - id: 15
    signed: true
    name: ov015
    object: ../../../build/usa/build/arm9_ov015.bin
    hash: 85dba9c538626a29
    delinks: overlays/ov015/delinks.txt
    symbols: overlays/ov015/symbols.txt
    relocations: overlays/ov015/relocs.txt
  - id: 16
    signed: true
    name: ov016
    object: ../../../build/usa/build/arm9_ov016.bin
    hash: 7b1d1e6136849893
    delinks: overlays/ov016/delinks.txt
    symbols: overlays/ov016/symbols.txt
    relocations: overlays/ov016/relocs.txt
  - id: 17
    signed: true
    name: ov017
    object: ../../../build/usa/build/arm9_ov017.bin
    hash: efeab4a1987dc0be
    delinks: overlays/ov017/delinks.txt
    symbols: overlays/ov017/symbols.txt
    relocations: overlays/ov017/relocs.txt
  - id: 18
    signed: true
    name: ov018
    object: ../../../build/usa/build/arm9_ov018.bin
    hash: a3051d1c98a8cc28
    delinks: overlays/ov018/delinks.txt
    symbols: overlays/ov018/symbols.txt
    relocations: overlays/ov018/relocs.txt
